export default {
    namespaced:true,//命名空间
    state:{
        goods: [
            {
                id:1,
                name:"魅族 16 Xs 全网通版",
                descrition:"8GB+256GB 星空蓝",
                price:"1499.00",
                reduct:"急速全面屏|4800W AI三摄|急速屏下指纹|4000mAh大电池|高通骁龙675|Onemind3.0|绚丽多彩色系",
                num:1,
                img:require("../assets/img/mei16xs.png"),
                Imges:[
                    require("../assets/img/mei16/mei16xs1.jpg"),
                    require("../assets/img/mei16/mei16xs2.jpg"),
                    require("../assets/img/mei16/mei16xs3.jpg"),
                    require("../assets/img/mei16/mei16xs4.jpg"),
                ],
            },
            {
                id:2,
                name:"魅族 17 Pro",
                descrition:"8GB+256GB 定白",
                price:"4299.00",
                reduct:"mSmart 5G 快省稳系统方案 | 高通骁龙 865 + UFS 3.1 + LPDDR5 | 6400W 全场景 AR 专业影像系统 27W 无线超充 + 4500mAh 超大电池",
                num:1,
                img:require("../assets/img/mei17pro.png"),
                Imges:[
                    require("../assets/img/mei17/mei17pro1.jpg"),
                    require("../assets/img/mei17/mei17pro2.jpg"),
                    require("../assets/img/mei17/mei17pro3.jpg"),
                    require("../assets/img/mei17/mei17pro4.jpg"),
                ],
            },
            {
                id:3,
                name:"魅族 17",
                descrition:"8GB+256GB 定白",
                price:"5399.00",
                reduct:"mSmart 5G 快省稳系统方案 | 高通骁龙 865 + UFS 3.1 高速闪存 | 6400W 全场景影像系统 定制三星 Super AMOLED 90 帧直屏 | 4500mAh 超大电池",
                num:1,
                img:require("../assets/img/mei17.png"),
                Imges:[
                    require("../assets/img/mei17/mei17pro1.jpg"),
                    require("../assets/img/mei17/mei17pro2.jpg"),
                    require("../assets/img/mei17/mei17pro3.jpg"),
                    require("../assets/img/mei17/mei17pro4.jpg"),
                ],
            },
            {
                id:4,
                name:"一加 8 Pro",
                descrition:"8GB+256GB 定白",
                price:"3699.00",
                reduct:"快省稳系统方案 | 高通骁龙 865 + UFS 3.1 高速闪存 | 6400W 全场景影像系统 定制三星 Super AMOLED 90 帧直屏 | 4500mAh 超大电池",
                num:1,
                img:require("../assets/img/yijia/jia8.webp"),
                Imges:[
                    require("../assets/img/yijia/jia81.webp"),
                    require("../assets/img/yijia/jia82.webp"),
                    require("../assets/img/yijia/jia83.webp"),
                    require("../assets/img/yijia/jia84.webp"),
                ],
            },
            {
                id:5,
                name:"一加 8",
                descrition:"8GB+256GB 定白",
                price:"3999.00",
                reduct:"快省稳系统方案 | 高通骁龙 865 + UFS 3.1 高速闪存 | 6400W 全场景影像系统 定制三星 Super AMOLED 90 帧直屏 | 4500mAh 超大电池",
                num:1,
                img:require("../assets/img/yijia/jia8pro.webp"),
                Imges:[
                    require("../assets/img/yijia/jia8pro1.webp"),
                    require("../assets/img/yijia/jia8pro2.webp"),
                    require("../assets/img/yijia/jia8pro3.webp"),
                    require("../assets/img/yijia/jia8pro4.webp"),
                ],
            },
            {
                id:6,
                name:"华为 Mate 30",
                descrition:"8GB+256GB 亮黑",
                price:"4499.00",
                reduct:"急速5G | 麒麟 990 + UFS 3.1 高速闪存 | 6400W 全场景影像系统 定制三星 Super AMOLED 90 帧直屏 | 4500mAh 超大电池",
                num:1,
                img:require("../assets/img/huawei/mate30.webp"),
                Imges:[
                    require("../assets/img/huawei/mate301.webp"),
                    require("../assets/img/huawei/mate302.webp"),
                    require("../assets/img/huawei/mate303.webp"),
                    require("../assets/img/huawei/mate304.webp"),
                ],
            },
            {
                id:7,
                name:"华为 p40 Pro",
                descrition:"8GB+256GB 亮黑",
                price:"4499.00",
                reduct:"急速5G | 麒麟 990 + UFS 3.1 高速闪存 | 6400W 全场景影像系统 定制三星 Super AMOLED 90 帧直屏 | 4500mAh 超大电池",
                num:1,
                img:require("../assets/img/huawei/p40pro.webp"),
                Imges:[
                    require("../assets/img/huawei/p40pro1.webp"),
                    require("../assets/img/huawei/p40pro2.webp"),
                    require("../assets/img/huawei/p40pro3.webp"),
                    require("../assets/img/huawei/p40pro4.webp"),
                ],
            },
            {
                id:8,
                name:"小米 10 Pro",
                descrition:"8GB+256GB 星空蓝",
                price:"4999.00",
                reduct:"快省稳系统方案 | 高通骁龙 865 + UFS 3.1 高速闪存 | 6400W 全场景影像系统 定制三星 Super AMOLED 90 帧直屏 | 4500mAh 超大电池",
                num:1,
                img:require("../assets/img/mi10pro.jpg"),
                Imges:[
                    require("../assets/img/xiaomi/mi10pro1.jpg"),
                    require("../assets/img/xiaomi/mi10pro2.jpg"),
                    require("../assets/img/xiaomi/mi10pro3.jpg"),
                    require("../assets/img/xiaomi/mi10pro4.jpg"),
                ],
            },
        ],
    },
    mutations:{
        
    },
    actions:{}
}