export default[
    {
        path:"/collec",
        name:"收藏",
        component:()=>import("../../components/my/collec.vue")
    },
    {
        path:"/coupon",
        name:"优惠券",
        component:()=>import("../../components/my/coupon.vue")
    },
    {
        path:"/envelopes",
        name:"红包",
        component:()=>import("../../components/my/envelopes.vue")
    },
    {
        path:"/kefu",
        name:"客服",
        component:()=>import("../../components/my/kefu.vue")
    },
    {
        path:"/messages",
        name:"消息",
        component:()=>import("../../components/my/messages.vue")
    },
    {
        path:"/evaluate",
        name:"评价",
        component:()=>import("../../components/my/evaluate.vue")
    },
    {
        path:"/footprint",
        name:"足迹",
        component:()=>import("../../components/my/footprint.vue")
    },
]
    